config/routes.rb
AjaxTest::Application.routes.draw do

  root :to => 'posts#index'

  get 'posts/badges' => 'posts#badges', :as => :badges

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def badges
    logger.debug(params.inspect)
    conn = Faraday.new(:url => 'http://api.stackoverflow.com') do |c|
      c.use Faraday::Request::UrlEncoded  # encode request params as "www-form-urlencoded"
      c.use Faraday::Response::Logger     # log request & response to STDOUT
      c.use Faraday::Adapter::NetHttp     # perform requests with Net::HTTP
    end

    response = conn.get '/1.1/badges'
    
    @badges = JSON.parse(response.body)["badges"].slice(0, 5)

    respond_to do |format|
      format.html
      format.json
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AjaxTest</title>
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_badges.html.erb
  <% @badges.each do |badge| %>
    <li><%= badge["description"] %></li>
  <% end %>

app/views/posts/badges.html.erb
<ul>
  <% @badges.each do |badge| %>
    <li><%= badge["description"] %></li>
  <% end %>
</ul>

app/views/posts/badges.js.erb
var el = $('#button-get-js').next();
<% @badges.each do |badge| %>
  el.append($('<li><%= escape_javascript(badge["description"]) %></li>'));
<% end %>

app/views/posts/badges.json.erb
[
  <% @badges.each do |badge| -%>
    { 
      "badge_id": "<%= badge["badge_id"].to_json -%>",
      "rank": "<%= badge["rank"].to_json -%>",
      "name": "<%= badge["name"].to_json -%>",
      "description": "<%= badge["description"].to_json -%>",
      "award_count": "<%= badge["award_count"].to_json -%>",
      "tag_based": "<%= badge["tag_based"].to_json -%>",
      "badges_recipients_url": "<%= badge["badges_recipients_url"].to_json -%>"
    }<%= ',' if badge != @badges.last -%>
  <% end -%>
]

app/views/posts/index.html.erb
<div id='title'>
  <h1>Here are samples of doing ajax in rails.</h1>
</div>

<div class='section'>
  <h2>1. Get a bundle of messages in json. </h2><button id="button-get-json">Get data in json</button>
  <ul>
  </ul>
</div>

<div class='section'>
  <h2>2. Show a bundle of messages in js. </h2><button id="button-get-js">Get data in js</button>
  <ul>
  </ul>
</div>

<div class='section'>
  <h2>3. Call the first test with a remote link. </h2><%= link_to 'Get data in json', badges_path(), :remote => "true", :"data-type" => "json", :id => 'link-get-json' %>
  <ul>
  </ul>
</div>